main/urls.py
from django.urls import path

from . import views
from .forms import CustomConfigForm, CustomResourceForm
from .models import CustomConfig, CustomResource

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path(
        "create_job/<int:project_pk>/<int:resource_index>/<int:software_index>/",
        views.create_job,
        name="create_job",
    ),
    path(
        "create_job/<int:project_pk>/<int:resource_index>/<int:software_index>/<int:config_pk>/",  # noqa: E501
        views.create_job,
        name="create_job",
    ),
    path("list_jobs/", views.list_jobs, name="list_jobs"),
    path("delete/<int:job_pk>/", views.delete, name="delete"),
    path("job_type/", views.job_type, name="job_type"),
    path("projects/", views.projects, name="projects"),
    path(
        "delete_project/<int:project_pk>/", views.delete_project, name="delete_project"
    ),
    path("job/<int:job_pk>/", views.job, name="job"),
    path(
        "software_help/<int:software_index>/", views.software_help, name="software_help"
    ),
    path("profile/", views.profile, name="profile"),
    path("delete_profile/", views.delete_profile, name="delete_profile"),
    path(
        "custom_config/",
        views.custom_config,
        {"form_class": CustomConfigForm},
        name="custom_config",
    ),
    path(
        "custom_config/<int:pk>/",
        views.custom_config,
        {"form_class": CustomConfigForm},
        name="custom_config",
    ),
    path(
        "custom_config/delete/<int:pk>/",
        views.custom_config_delete,
        {"klass": CustomConfig},
        name="custom_config_delete",
    ),
    path(
        "custom_config/resource/",
        views.custom_config,
        {"form_class": CustomResourceForm},
        name="custom_resource",
    ),
    path(
        "custom_config/resource/<int:pk>/",
        views.custom_config,
        {"form_class": CustomResourceForm},
        name="custom_resource",
    ),
    path(
        "custom_config/resource/delete/<int:pk>/",
        views.custom_config_delete,
        {"klass": CustomResource},
        name="custom_resource_delete",
    ),
    path("download/<int:job_pk>/", views.download, name="download"),
    path("authorize/<str:repo_label>/", views.authorize, name="authorize"),
    path("token/<str:repo_label>/", views.token, name="token"),
    path("publish/<int:job_pk>/", views.publish, name="publish"),
    path("delete_token/<str:repo_label>/", views.delete_token, name="delete_token"),
    path("directory/<int:job_pk>/", views.directory, name="directory"),
]

main/models/custom.py
from django.db import models

from ..validators import validate_config_lines


class Custom(models.Model):
    """An abstract class for custom content to be added to job script templates."""

    class Meta:
        abstract = True

    label = models.CharField(max_length=50)
    script_lines = models.TextField(max_length=1000, validators=[validate_config_lines])

    def __str__(self):
        return f"{self.label}"


class CustomConfig(Custom):
    """Custom scheduler directives not related to job resources."""

    pass


class CustomResource(Custom):
    """Custom scheduler directives related to job resources."""

    pass

main/forms.py
from django import forms

from .models import CustomConfig, CustomResource, Job, Profile, Project
from .resources import get_resource_choices
from .software import get_software_choices


class SubmissionForm(forms.Form):
    """Used in the final step before job submission in the create_job view. Form fields
    are generated based on the software configuration provided.
    """

    required_css_class = "required"

    def __init__(self, software, *args, **kwargs):
        """
        args:
          software (dict): The software package on which to base the form. Must follow
            config_validation.SoftwareSchema.
          *args: passed through to base class init method
          **kwargs: passed through to base class init method
        """
        super().__init__(*args, **kwargs)
        self.fields["description"] = forms.CharField(
            max_length=200, label="Description", required=False
        )
        input_files = software["input_files"]
        for spec in input_files["required"]:
            self.fields[spec["key"]] = forms.FileField(label=spec["description"])
        for spec in input_files["optional"]:
            self.fields[spec["key"]] = forms.FileField(
                label=spec["description"], required=False
            )


class JobTypeForm(forms.Form):
    """Used in the initial step of job creation in the job_type view."""

    required_css_class = "required"
    project = forms.ModelChoiceField(
        Project.objects.all(),
        label="Project",
        empty_label=None,
    )
    resources = forms.ChoiceField(
        label="Job Resources",
        choices=get_resource_choices,
    )
    software = forms.ChoiceField(
        label="Software",
        choices=get_software_choices,
    )
    custom_config = forms.ModelChoiceField(
        CustomConfig.objects.all(),
        label="Custom Configuration",
        to_field_name="label",
        required=False,
    )

    run_another = forms.BooleanField(
        widget=forms.CheckboxInput(
            attrs={"class": "ui checkbox",
                   "style": "margin-top: 3px; margin-left: 8px;"}
        ),
        label="Run another job after submission:",
        required=False)


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = "__all__"


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["description", "project"]


class CustomConfigForm(forms.ModelForm):
    class Meta:
        model = CustomConfig
        fields = "__all__"
        help_texts = {
            "script_lines": "Lines placed here are used as scheduler directives for new jobs. Resource specifications may not be provided here and will not be honoured."  # noqa: E501
        }


class CustomResourceForm(forms.ModelForm):
    class Meta:
        model = CustomResource
        fields = "__all__"
        help_texts = {
            "script_lines": "Lines should be valid scheduler directives that specify job resource requirements. Other lines may also be necessary e.g. setting environment variables. It is strongly suggested that you use a system resource configuration as a reference..",  # noqa: E501
            "label": "When a job is run using this resource configuration only the label is recorded. Therefore it is important that you provide a label that is clear and descriptive of the resources used.",  # noqa: E501
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"

main/views.py
import csv
import logging
import os
from datetime import timedelta
from itertools import chain

import django_tables2 as tables
from django.conf import settings
from django.core.exceptions import ValidationError
from django.http import Http404, StreamingHttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from . import scheduler
from .filters import JobFilter
from .forms import JobForm, JobTypeForm, ProfileForm, ProjectForm, SubmissionForm
from .models import (
    CustomConfig,
    CustomResource,
    Job,
    Profile,
    Project,
    Publication,
    Token,
)
from .portal_config import get_portal_settings
from .repositories import RepositoryError, get_repositories, get_repository
from .software import get_software
from .tables import (
    CustomConfigTable,
    CustomResourceTable,
    DirectoryTable,
    JobTable,
    PublicationTable,
)
from .utils import file_properties
from .zip_stream import zipfile_generator

logger = logging.getLogger(__name__)


def index(request):
    """The index view"""
    admin_email = settings.ADMINS[0][1] if settings.ADMINS else ""
    return render(request, "main/index.html", {"admin_email": admin_email})


def about(request):
    """The about view"""
    return render(request, "main/about.html")


def create_job(request, project_pk, resource_index, software_index, config_pk=None):
    """This view handles a form that when submitted triggers creation of a job.

    args:
      request (HttpRequest): request that triggered this view
      project_pk (int): pk of the project for this job
      resource_index (int): index of the resource configuration for this job
      software_index (int): index of the sofware configuration for this job
      config_pk (int): pk of the CustomConfig record for this job

    returns:
      (HttpResponse): the page to display
    """
    project = get_object_or_404(Project, pk=project_pk)
    software = get_software()[software_index]
    custom_config = (
        None if config_pk is None else get_object_or_404(CustomConfig, pk=config_pk)
    )
    if request.method == "POST":
        form = SubmissionForm(software, request.POST, request.FILES)
        files_spec = software["input_files"]
        if form.is_valid():
            input_files = {
                spec["key"]: request.FILES[spec["key"]]
                for spec in chain(files_spec["required"], files_spec["optional"])
                if spec["key"] in request.FILES
            }
            try:
                job = Job.objects.create_job(
                    form.cleaned_data["description"],
                    input_files,
                    project,
                    resource_index,
                    software_index,
                    custom_config,
                )
                url = reverse("main:list_jobs")
                return redirect(url + f"?success={job.pk}")
            except scheduler.SchedulerError as e:
                logger.exception("Exception during job submission")
                msg = f"Job submission failed\n\n{e.args[0]}"
                return render(request, "main/failed.html", {"message": msg})
    else:
        form = SubmissionForm(software)
    return render(
        request,
        "main/create_job.html",
        {
            "form": form,
            "software_help_url": reverse(
                "main:software_help", kwargs={"software_index": software_index}
            ),
        },
    )


def list_jobs(request):
    """The list view used to display jobs that have submitted via the portal. An
    important secondary function is to update job records when they complete.

    args:
      request (HttpRequest): request that triggered this view

    returns:
      (HttpResponse): the page to display
    """
    job_filter = JobFilter(request.GET, queryset=Job.objects.order_by("-pk"))
    table = JobTable(job_filter.qs)
    config = tables.RequestConfig(request, paginate={"per_page": 15})
    config.configure(table)

    portal_settings = get_portal_settings()
    for job in table.page.object_list.data:
        if job.status != Job.COMPLETED:
            try:
                job.status = scheduler.status(
                    job.job_id, timeout=portal_settings.TIMEOUTS["status"]
                ).capitalize()[0]
            except scheduler.SchedulerError:
                # if something goes wrong with getting status info for one
                # job, assume a problem and don't try the rest
                break
            if job.status == Job.COMPLETED:
                try:
                    with (job.work_dir / "WALLTIME").open() as f:
                        job.walltime = timedelta(seconds=int(f.read()))
                except (IOError, ValueError):
                    pass
            job.save()

    try:
        job = Job.objects.get(pk=int(request.GET["success"]))
        message = f"Successfully submitted job - {job.job_number} ({job.job_id})"
    except (KeyError, Job.DoesNotExist, ValueError):
        message = None
    return render(
        request,
        "main/list_jobs.html",
        {
            "table": table,
            "filter": job_filter,
            "options": (10, 15, 25, 50),
            "message": message,
        },
    )


def delete(request, job_pk):
    """Delete a job from the database.

    args:
      request (HttpRequest): request that triggered this view
      job_pk (int): the pk of the job to delete

    returns:
      (HttpResponseRedirect): a redirect to previous view
    """
    job = get_object_or_404(Job, pk=job_pk)
    try:
        job.delete()
    except (scheduler.SchedulerError, OSError):
        logger.exception(f"Error deleting job: Job pk {job.pk}")
        return render(
            request,
            "main/failed.html",
            {
                "message": (
                    "Error encountered whilst deleting job. Please try again later."
                )
            },
        )
    except FileNotFoundError:
        pass
    return redirect(request.META.get("HTTP_REFERER", "main:index"))


def job_type(request):
    """Handles the initial form for job creation.

    args:
      request (HttpRequest): request that triggered this view

    returns:
      (HttpResponse or HttpResponseRedirect): a page or redirect to next form view
    """
    if request.method == "POST":
        form = JobTypeForm(request.POST)
        if form.is_valid():
            project = form.cleaned_data["project"]
            args = [form.cleaned_data["resources"], form.cleaned_data["software"]]
            custom_config = form.cleaned_data["custom_config"]
            if custom_config:
                args.append(custom_config.pk)
            return redirect("main:create_job", project.pk, *args)
    else:
        form = JobTypeForm()
    return render(
        request,
        "main/job_type.html",
        {
            "form": form,
            "config_link": get_portal_settings().CONFIG_LINK,
        },
    )


def projects(request):
    """Displays existings projects and a form to create new projects

    args:
      request (HttpRequest): request that triggered this view

    returns:
      (HttpResponse or HttpResponseRedirect): a page or redirect to the previous view
    """
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(request.META.get("HTTP_REFERER", "main:index"))
    else:
        form = ProjectForm()
    projects = Project.objects.all()
    return render(request, "main/projects.html", {"projects": projects, "form": form})


def delete_project(request, project_pk):
    """Delete a project from the database.

    args:
      request (HttpRequest): request that triggered this view
      project_pk (int): the pk of the job to delete

    returns:
      (HttpResponseRedirect): a redirect to previous view
    """
    get_object_or_404(Project, pk=project_pk).delete()
    return redirect(request.META.get("HTTP_REFERER", "main:index"))


def job(request, job_pk):
    """Detailed information for a single job. Handles a form allowing update of the
    job.

    args:
      request (HttpRequest): request that triggered this view
      job_pk (int): the pk of the job to displayg

    returns:
      (HttpResponse or HttpResponseRedirect): a page or redirect to the previous view
    """
    job = get_object_or_404(Job, pk=job_pk)
    form = JobForm(request.POST or None, instance=job)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(request.META.get("HTTP_REFERER", "main:index"))
    table = PublicationTable(Publication.objects.filter(job=job))
    return render(request, "main/job.html", {"form": form, "table": table})


def software_help(request, software_index):
    """Displays the detailed help text associated with a software.

    args:
      request (HttpRequest): request that triggered this view
      software_index (int): the index of the software for which to display the help text

    returns:
      (HttpResponse): the page to display
    """
    software = get_software()[software_index]
    return render(
        request, "main/software_help.html", {"help_text": software["help_text"]}
    )


def profile(request):
    """Display details of users profile information and linked data
    repositories. Assumes existence of no more than one Profile record. If
    present, the existing record is displayed as pre-populated fields in a
    form. All enabled repositories are displayed in a table. A repository is
    considered linked if there is an associated Token record.

    args:
      request (HttpRequest): request that triggered this view

    returns:
      (HttpResponse or HttpResponseRedirect): a page or redirect to the previous view
    """
    try:
        profile = Profile.objects.get()
    except Profile.DoesNotExist:
        profile = Profile()

main/templates/main/about.html
{% extends "main/base.html" %}
{% block content %}
<div class="ui text container">
  <h1 class="ui header">About CHAMP</h1>
  <p>
    <strong>CHAMP v{{ APP_VERSION }}<br/></strong>
    &copy; 2021 Imperial College London
  </p>
  <p>
    CHAMP is a web browser-based tool for simplifying the submission of
    computational tasks to High Performance Computing (HPC) infrastructure.
  </p>
  <p>
    Avoid the need to learn about using the command line, connecting to remote
    system using tools like SSH or writing job submission scripts. Get the
    benefits of HPC processing power directly through your browser!
  </p>

  <h3 class="ui header">Citing CHAMP</h3>
  <p>
    If you make use of CHAMP to support your research work, please cite the
    following publication:
  </p>
  <p>
    C. Cave-Ayland, M. Bearpark, C. Romain, H. Rzepa. CHAMP is a HPC Access and
    Metadata Portal.<br/><em>Journal of Open Source Software</em>
    <strong>2022</strong>, 7 (70), 3824.
    <a href="https://doi.org/10.21105/joss.03824" target="_blank"
       rel="noopener noreferrer">
       https://doi.org/10.21105/joss.03824
    </a>
  </p>

  <h4 class="ui header">Related publications</h4>
  <p>
    M. J. Harvey, N. J. Mason and H. S. Rzepa. Digital data repositories in
    chemistry and their integration with journals and electronic
    laboratory notebooks, <em>J. Chem. Inf. Model.</em>,
    <strong>2014</strong>, 54, 2627–2635.<br/> DOI:
    <a href="https://doi.org/10.1021/ci500302p" target="_blank"
       rel="noopener noreferrer">10.1021/ci500302p</a>
  </p> 
</div>
{% endblock content %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{{ APP_NAME }}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'main/favicon-32x32.png' %}">
    <link rel="stylesheet" href="{% static 'main/css/semantic.min.css' %}">
    <style>
	{% include MENU_STYLE_TEMPLATES %}

        .grid.container {
            margin-top: 5em;
        }

	.errorlist {
	    color: red;
	}

	/* add arrows to end of headers for sorted columns  */
	.orderable {
	    white-space: nowrap;
	}
	.asc.orderable::after {
	    display: inline-block;
	    text-rendering: auto;
	    font-family: "Icons";
	    content: '\f106';
	}
	.desc.orderable::after {
	    display: inline-block;
	    text-rendering: auto;
	    font-family: "Icons";
	    content: '\f107';
	}
	label.required::after {
	    content: " *";
	    color: red;
	}
    </style>
</head>

<body>
    <div class="ui fixed inverted menu">
        <div class="ui container">
            <a href="{% url 'main:index' %}" class="header item">
                <img class="logo" alt="logo" src="{% static 'main/logo.png' %}">
            </a>
            <a href="{% url 'main:projects' %}" class="item">Projects</a>
            <a href="{% url 'main:job_type' %}" class="item">Create Job</a>
            <a href="{% url 'main:list_jobs' %}" class="item">List All Jobs</a>
            <a href="{% url 'main:profile' %}" class="item">Profile</a>
            {% for link in EXTERNAL_LINKS %}
            <a href="{{ link.url }}" target="_blank" class="item external-link">{{ link.text }}</a>
            {% endfor %}
            <div class="right menu">
                <a href="{% url 'main:about' %}" class="item">About CHAMP</a>
                <div class="item">{{ APP_NAME }} v{{ APP_VERSION }}</div>
            </div>
        </div>
    </div>

    <div class="ui grid container">
      {% block content %}{% endblock %}
    </div>
    <script src="{% static 'main/js/jquery.min.js' %}"></script>
    <script src="{% static 'main/js/semantic.min.js' %}"></script>

    <script>
      $('.external-link').popup({
	  content: 'This link opens a new tab outside the portal site. Please close the tab to return to the portal.'
      })
      $('.blocking').popup({
	  content: 'Site will be unresponsive until action completed.'
      })
    </script>

    {% block footer %}
    <div class="ui grid container">
        <div class="ui text container">
            <span>&copy;</span> Imperial College London 2021
        </div>
    </div>
    {% endblock %}
</body>

</html>

main/templates/main/create_job.html
{% extends "main/base.html" %}
{% block content %}
{% if not content %}
<div class="ui text container">
  <p><a href="{{ software_help_url }}">Detailed information for preparing inputs</a></p>
  <form class="ui form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
      {{ field.label_tag }}
      {{ field }}
    </div>
    {% endfor %}
    <input class="ui button" type="submit" value="Submit">
  </form>
</div>
{% endif %}
{% endblock %}

main/templates/main/custom_config.html
{% extends "main/base.html" %}
{% block content %}
{% if not content %}

<div class="ui text container">
  <h2 class="ui header">Custom Configuration</h2>
  <form class="ui form" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
      {{ field.label_tag }}
      {{ field }}
      <p>{{ field.help_text }}</p>
      {{ field.errors }}
    </div>
    {% endfor %}
    <input class="ui button" type="submit" value="{% if create %}Create{% else %}Update{% endif %}">
  </form>
</div>
{% endif %}
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block title %}{{ APP_NAME }} | Home{% endblock %}

{% block content %}
<div class="ui text container">
  {% include INDEX_PAGE_TEMPLATES %}
</div>
{% endblock %}

main/templates/main/job.html
{% extends "main/base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
{% if not content %}

<div class="ui text container">
  <a href="{% url 'main:list_jobs' %}">Back to job list</a>
  <h2 class="ui header">Edit Job Information</h2>
  <form class="ui form" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
      {{ field.label_tag }}
      {{ field }}
    </div>
    {% endfor %}
    <input class="ui button" type="submit" value="Update">
  </form>
  <h2 class="ui header">Publication Records</h2>
  {% render_table table %}
</div>

{% endif %}
{% endblock %}

main/templates/main/job_type.html
{% extends "main/base.html" %}
{% block content %}
{% if not content %}
<div class="ui text container">
  <h2 class="ui header">Create a New Job</h2>
  <form class="ui form" method="post">
    {% csrf_token %}
    <table style="width:100%; padding-bottom: 10px;">
      <tbody>
	<tr>
	  <td width="70%">
	    <div class="field">
	      {{ form.project.label_tag }}
	      {{ form.project }}
	    </div>
	  </td>
	  <td style="vertical-align:bottom">
	    <a href="{% url 'main:projects' %}">or create a new project</a>
	  </td>
	</tr>
	{% if form.project.errors %}
	<tr>
	  <td>
	    {{ form.project.errors }}
	  </td>
	</tr>
	{% endif %}
      </tbody>
    </table>
    <div class="field">
      {{ form.resources.label_tag }}
      {{ form.resources }}
      {{ form.resources.errors }}
    </div>
    {% if config_link %}
    <table style="width:100%; padding-bottom: 10px;">
      <tbody>
	<tr>
	  <td width="70%">
	    <div class="field">
    {% endif %}
    <div class="field">
      {{ form.software.label_tag }}
      {{ form.software }}
      {% if not config_link %}{{ form.software.errors }}{% endif %}
    </div>
    {% if config_link %}
	  </td>
	  <td style="vertical-align:bottom">
	    <a href="{{ config_link }}">or add a new software</a>
	  </td>
	</tr>
	{% if form.project.errors %}
	<tr>
	  <td>
	    {{ form.project.errors }}
	  </td>
	</tr>
	{% endif %}
      </tbody>
    </table>
    {% endif %}
    <div class="field">
      {{ form.custom_config.label_tag }}
      {{ form.custom_config }}
      {{ form.custom_config.errors }}
    </div>
    <div>
        <input class="ui button" type="submit" value="Submit">
        <span style="float: right; margin-top: 8px;">
          <label for="{{ form.run_another_for_label }}" >{{ form.run_another.label }}</label>
          {{ form.run_another }}
        </span>
    </div>
  </form>
</div>
{% endif %}
{% endblock %}

main/templates/main/list_jobs.html
{% extends "main/base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
{% if not content %}

{% if message %}
<div class="row">
  <div class="ui text container">
    <div class = "ui positive message">
      {{ message }}
    </div>
  </div>
</div>
{% endif %}

<div class="row">
  <div class="ui text container">
    <h2 class="ui header">Job List</h2>
    <form class="ui form" method="get">
      <div class="field">
	{{ filter.form.description.label_tag }}
	{{ filter.form.description }}
      </div>
      <div class="field">
	<label>{{ filter.form.not_description.label }}</label>
	{{ filter.form.not_description }}
      </div>
      <div class="fields">
	<div class="field">
	  <label>{{ filter.form.project.label }}</label>
	  {{ filter.form.project }}
	</div>
	<div class="field">
	  <label>{{ filter.form.status.label }}</label>
	  {{ filter.form.status }}
	</div>
	<div class="field">
	  <label>{{ filter.form.resources.label }}</label>
	  {{ filter.form.resources }}
	</div>
	<div class="field">
	  <label>{{ filter.form.software.label }}</label>
	  {{ filter.form.software }}
	</div>
      </div>
      <div class="fields">
	<div class="field">
	  <label>Results per page</label>
	  <select name="per_page" id="id_per_page" onchange="this.form.submit()">
	    {% for value in options %}
	    <option value={{value}}{% if value == table.paginator.per_page %} selected{% endif %}>{{ value }}</option>
	    {% endfor %}
	  </select>
	</div>
      </div>

      <input value="Filter" class="ui button" type="submit">
      <a class="ui button" href="{% url 'main:list_jobs' %}">Reset Filter</a>

    </form>
  </div>
</div>
<div class="row">
  {% render_table table %}
</div>
{% endif %}
{% endblock %}

main/templates/main/menu_style.html
.ui.inverted.menu {
  background-color: #003E74;
}

.ui.inverted.menu .item {
  color: #FFFFFF;
}

.ui.menu .item img.logo {
  margin-right: 5em;
  min-height: 100%;
  min-width: 100%;
}

main/templates/main/profile.html
{% extends "main/base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
{% if not content %}
<div class="row">
  <div class="ui text container">
    <h2 class="ui header">Profile</h2>
    <form class="ui form" method="post">
      {% csrf_token %}
      {% for field in form %}
      <div class="field">
	{{ field.label_tag }}
	{{ field }}
	{{ field.errors }}
      </div>
      {% endfor %}
      <input class="ui button" type="submit" value="Update"><a href="{% url 'main:delete_profile' %}"><div class="ui button">Delete all info</div></a>
    </form>
  </div>
</div>

<div class="row">
  <div class="ui text container">
    <h3 class="ui header">Data Repositories</h3>
    <table class="ui celled table">
      <thead>
	<tr>
	  <th>Name</th>
	  <th>Status</th>
	  <th></th>
	</tr>
      </thead>
      <tbody>
	{% for repo in repository_data %}
	<tr>
	  <td>{{ repo.name }}</td>
	  <td>{% if repo.linked %}Linked{% else %}Unlinked{% endif %}</td>
	  {% if repo.linked %}
	  <td><a href="{% url 'main:delete_token' repo.label %}">Unlink</a></td>
	  {% else %}
	  <td><a href="{% url 'main:authorize' repo.label %}">Link</a></td>
	  {% endif %}
	<tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="ui text container">
    <h3 class="ui header">Custom Job Script Configurations (Advanced)</h3>
    <p>Use to provide additional configuration when you run jobs e.g. to provide accounting information or access to a private queue.</p>
    {% if configs_table.rows|length != 0 %}
    {% render_table configs_table %}
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="ui text container">
    <a class="ui button" href="{% url 'main:custom_config' %}">Create a new custom configuration</a>
  </div>
</div>
<div class="row">
  <div class="ui text container">
    <h3 class="ui header">Custom Resource Configurations (Advanced)</h3>
    <p>Use these to run jobs with a customised set of resources. Once created, the configuration will appear in the Job Resources dropdown on the Create Job page.</p>
    {% if resource_table.rows|length != 0 %}
    {% render_table resource_table %}
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="ui text container">
    <a class="ui button" href="{% url 'main:custom_resource' %}">Create a new resource configuration</a>
  </div>
</div>
{% endif %}
{% endblock %}

main/templates/main/projects.html
{% extends "main/base.html" %}
{% block content %}
{% if not content %}

<div class="ui text container">
  <h2 class="ui header">Projects</h2>

  <p>You may define projects to organise your jobs. A job is assigned a
    project when it is run; you may reassign it later.</p>

  <h3 class="ui header">Existing Projects</h3>
  <table class="ui celled table">
    <thead>
      <tr>
	<th>Name</th>
	<th>No. Jobs</th>
	<th></th>
      </tr>
    </thead>
    <tbody>
      {% for project in projects %}
      <tr>
	<td>{{ project.name }}</td>
	<td>{{ project.number_of_jobs }}</td>
	<td><a href="{% url 'main:delete_project' project.pk %}">Delete project</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <h3 class="ui header">Add a New Project</h3>
  <form class="ui form" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
      {{ field.label_tag }}
      {{ field }}
    </div>
    {% endfor %}
    <input class="ui button" type="submit" value="Add">
  </form>
</div>
{% endif %}
{% endblock %}

main/templates/main/software_help.html
{% extends "main/base.html" %}
{% block content %}
{% if not content %}

<div class="ui text container">
  {{ help_text |safe }}
</div>

{% endif %}
{% endblock %}

main/templates/main/welcome.html
    <h1>{{ APP_NAME }}</h1>
    <p>Welcome to {{ APP_NAME }}. You can use this web portal to run instances of
      packaged applications on a high performance computing system.</p>

    <p>Create a new job by selecting <a href="{% url 'main:job_type' %}">
	Create Job</a> from the top menu. Individual jobs
      may be associated with a particular <a href="{% url 'main:projects' %}">
	project</a>. To see all jobs,
      past and present, select <a href="{% url 'main:list_jobs' %}">
	List All Jobs</a>.</p>

    <p>For information, <a href="mailto:{{ admin_email }}">contact the admin</a>.</p>